# Generated by Django 2.2.5 on 2020-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10, unique=True)),
                ('pastword', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
