# Generated by Django 2.2.5 on 2020-02-09 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20200202_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='res',
            field=models.CharField(default=111, max_length=10),
            preserve_default=False,
        ),
    ]
