# Generated by Django 2.2.5 on 2020-02-09 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_user_res'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='res',
        ),
    ]
