# Generated by Django 2.2.5 on 2020-02-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_remove_user_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pastword',
            new_name='password',
        ),
    ]
