# Generated by Django 2.2.5 on 2020-02-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20200209_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('musicbrainzArtistId', models.CharField(max_length=10)),
                ('artistName', models.CharField(max_length=10)),
                ('musicbrainzTrackId', models.CharField(max_length=10)),
                ('trackName', models.CharField(max_length=10)),
            ],
        ),
    ]
