# Generated by Django 2.2.5 on 2020-02-16 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_registry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='artistName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registry',
            name='musicbrainzArtistId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registry',
            name='musicbrainzTrackId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registry',
            name='trackName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registry',
            name='userId',
            field=models.CharField(max_length=100),
        ),
    ]
