# Generated by Django 2.2.5 on 2020-02-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_auto_20200216_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registry',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
