# Generated by Django 2.2.5 on 2020-03-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0010_prediction_chart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
